### ISSUE TITLE
Members 페이지 구현

### ISSUE THREAD

**Issue by ghkim3221** [openpnu/openpnu.github.io#26]
openpnu 동아리 회원 정보를 보여줄 수 있는 페이지가 있으면 좋을 것 같습니다.

**Comment by nono5546** [comment]
동아리 회원 정보가 어디까지 공개될 예정인가요?

**Comment by gihwanxyz** [comment]
> 동아리 회원 정보가 어디까지 공개될 예정인가요?

이름, 관심 분야, 이메일 주소 등이 어떨까요.

**Comment by Seo-GwangHyeon** [comment]
기왕하는거 각 회원 git이나 블로그 있으면 블로그정도가 좋을거 같습니다.
